#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

# Optional toggles:
#   RUN_MYPY=1 ./scripts/lint.sh
#   RUN_CLANG_TIDY=1 ./scripts/lint.sh
RUN_MYPY="${RUN_MYPY:-0}"
RUN_CLANG_TIDY="${RUN_CLANG_TIDY:-0}"

echo "==> Python lint (ruff check)..."
ruff check .

echo "==> Python format check (ruff format --check)..."
ruff format . --check

# Optional: mypy
if [ "$RUN_MYPY" = "1" ]; then
  echo "==> mypy (optional)..."
  if ! command -v mypy >/dev/null 2>&1; then
    echo "ERROR: mypy not found in PATH. Install it (pip/conda) or run without RUN_MYPY=1."
    exit 1
  fi

  # For ROS2 Python packages, type checking can be tricky due to generated interfaces.
  # Start conservative: only check your python package code under robot_ws/src.
  # You can tighten later per-package.
  mypy robot_ws/src \
    --ignore-missing-imports \
    --show-error-codes
else
  echo "==> mypy skipped (set RUN_MYPY=1 to enable)."
fi

# Optional: clang-tidy
if [ "$RUN_CLANG_TIDY" = "1" ]; then
  echo "==> clang-tidy (optional)..."
  if ! command -v clang-tidy >/dev/null 2>&1; then
    echo "ERROR: clang-tidy not found in PATH. Install it or run without RUN_CLANG_TIDY=1."
    exit 1
  fi

  # clang-tidy needs compile_commands.json (generated by CMake).
  # In ROS2, easiest is to build with:
  #   colcon build --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
  #
  # Then locate compile_commands.json. Depending on colcon, it may exist per-package.
  # We'll search in robot_ws/build/**/compile_commands.json.
  mapfile -t CCDBS < <(find "$ROOT_DIR/robot_ws/build" -name compile_commands.json -type f 2>/dev/null || true)

  if [ "${#CCDBS[@]}" -eq 0 ]; then
    echo "ERROR: No compile_commands.json found."
    echo "Build first with:"
    echo "  colcon build --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
    exit 1
  fi

  # Choose first database by default; you can set CLANG_TIDY_DB=/path/to/compile_commands.json
  CLANG_TIDY_DB="${CLANG_TIDY_DB:-${CCDBS[0]}}"
  echo "Using compile database: $CLANG_TIDY_DB"

  # Run clang-tidy on files in robot_ws/src (C/C++ only)
  mapfile -t CPP_FILES < <(
    find "$ROOT_DIR/robot_ws/src" \
      -type f \( -name "*.c" -o -name "*.cc" -o -name "*.cpp" -o -name "*.cxx" -o -name "*.h" -o -name "*.hpp" \) \
      -not -path "*/build/*" -not -path "*/install/*" -not -path "*/log/*" \
      -print
  )

  if [ "${#CPP_FILES[@]}" -eq 0 ]; then
    echo "No C/C++ files found under robot_ws/src. Skipping clang-tidy."
  else
    # You can tune checks via a .clang-tidy file later.
    # For now, run with default checks.
    clang-tidy -p "$CLANG_TIDY_DB" "${CPP_FILES[@]}"
  fi
else
  echo "==> clang-tidy skipped (set RUN_CLANG_TIDY=1 to enable)."
fi

echo "✅ Lint complete."